### ISSUE TITLE
usage instructions

### ISSUE THREAD

**Issue by damo2929** [demosjarco/Cloudflare-Teams-DNS-Privacy-AdBlock#2]
Hi interested in using this but don't see anything on setting it up or using it.
cftdpa.pages.dev also results in none usable page.

would it be possible to document how this is meant to work.

**Comment by demosjarco** [comment]
This project is still very early in development, not yet done. I try to keep more of the work organized in branches. As it says in the readme, you can put the branch name as a subdomain to see the live version of it
